#%RAML 0.8
title: biztraveller
version: 1.0
baseUri: https://biztraveller.co.uk/api

schemas:
  - sfdc_lead: !include schemas/sfdc_leads_schema.json
  - event: !include schemas/event_schema.json
 
/events:
  displayName: Retrieve Events
  get:
    description: | 
      Retrieve List of events from Salesforce and Google calendar.
      * If both Salesforce and Google available, result_type = full
      * if only one system is available, result_type=partial
      * If no systems are available, an error is thrown, and a 500 is returned
    responses:
      200:
        description: OK
        body: 
          application/json: 
            example: !include ./examples/sfdc_google_events_example.json
            schema: event
      401:
        description: Invalid credentials
        body:
          appliation/json:
            example: | 
              {
                "message": "Invalid Credentials"
              }         
      404:
        description: Error Retrieving Event
        body: 
          application/json: 
            example: | 
              {
                "message": "Could not retrieve Leads"
              }
      500:
        description: Error Retrieving Events from Salesforce and Google Calendar
        body: 
          application/json: 
            example: | 
              {
                "message": "Cannot reach Salesforce or Google Calendar to retrieve events"
              }
        
/customer_leads:
  displayName: Retrieve Customer Leads
  get:
    description: Retrieve List of customer leads from Salesforce
    responses:
      200:
        description: OK
        body:
          application/json: 
            example: !include ./examples/sfdc_leads_example.json
            schema: sfdc_lead
      401:
        description: Invalid credentials
        body:
          appliation/json:
            example: | 
              {
                "message": "Invalid Credentials"
              }         
      404:
        description: Error Retrieving Leads
        body: 
          application/json: 
            example: | 
              {
                "message": "Could not retrieve Leads"
              }
